apiVersion: v1 
kind: Service 
metadata:
  name: presto-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- if .Values.ingress.annotations }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{.Values.ingress.type}}
  ports:
    - port: {{.Values.ingress.port}}
  selector:
    role: coordinator
  source:
    repoURL: https://github.com/Lokeshyogi/ingress.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
