apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: presto-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: http
      protocol: {{ .Values.gateway.protocol }}
    {{- if .Values.gateway.hosts }}
    {{- with .Values.gateway.hosts }}
    hosts:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  project: default
  source:
    repoURL: https://github.com/Lokeshyogi/gateway.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true





