apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: presto-vs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  {{- if .Values.virtualService.hosts }}
  {{- with .Values.virtualService.hosts }}
  hosts:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  gateways:
    - presto-gateway
  http:
    - match:
        - uri:
            regex: /.*
      route:
        - destination:
            host: presto-ingress.argo-presto-vikas.svc.cluster.local
            port:
              number: 8080
          weight: 50
        - destination:
            host: presto-ingress.argo-presto-prab.svc.cluster.local
            port:
              number: 8080
          weight: 50
  source:
    repoURL: https://github.com/Lokeshyogi/virtual-service.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
